### ISSUE TITLE
TimeoutError: Navigation timeout of 30000 ms exceeded -- When State Code feature not enabled

### ISSUE THREAD

**Issue by bobbywhitesfdc** [anandbn/notmeta#1]
**sfdx state_country:validate -u FSCDEMO**
TimeoutError: Navigation timeout of 30000 ms exceeded
    at /Users/bobby.white/projects/notmeta/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
    at FrameManager.waitForFrameNavigation (/Users/bobby.white/projects/notmeta/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:127:23)
    at Frame.waitForNavigation (/Users/bobby.white/projects/notmeta/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:441:16)
    at Page.waitForNavigation (/Users/bobby.white/projects/notmeta/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:794:16)
    at Validate.run (/Users/bobby.white/projects/notmeta/src/commands/state_country/validate.ts:63:13)
    at Validate._run (/Users/bobby.white/projects/notmeta/node_modules/@salesforce/command/lib/sfdxCommand.js:91:40)
    at Config.runCommand (/Users/bobby.white/.local/share/sfdx/client/7.84.2-a2868a68d5/node_modules/@oclif/config/lib/config.js:173:24)
    at Main.run (/Users/bobby.white/.local/share/sfdx/client/7.84.2-a2868a68d5/node_modules/@oclif/command/lib/main.js:27:9)
    at Main._run (/Users/bobby.white/.local/share/sfdx/client/7.84.2-a2868a68d5/node_modules/@oclif/command/lib/command.js:43:20)
    at Object.run (/Users/bobby.white/.local/share/sfdx/client/7.84.2-a2868a68d5/dist/cli.js:32:20)
Country and State picklist validation... done

Background here.  I'm running this against a scratch org.   I'd never gone through and enabled the State & Country Picklists feature in setup.   

**Expected**:  This validation command would fail gracefully if the feature hadn't been enabled.

**Comment by anandbn** [comment]
This tends to happen sporadically. Right now the workdaround is below:

```
sfdx auth:logout -u <the username of the org>
```

Once the logout is complete, do 

```
sfdx auth:web:login
```

and login to the same org. Once you complete login, attempt the `validate` and `load` commands.

**Comment by bobbywhitesfdc** [comment]
Sfdx auth:web:login (reauthenticate approach) is completely unnatural for scratch orgs.
Am I incorrect in thinking that this behavior has nothing to do with timeout of frontdoor.jsp on authentication and everything to do with having never enabled the feature in setup?
