### ISSUE TITLE
state_country:load -- TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by bobbywhitesfdc** [anandbn/notmeta#2]
**sfdx state_country:load -u FSCDEMO -c test_states.csv -s test_countries.csv** 
Loading countries from : test_states.csv
Loading states from : test_countries.csv
Take Screenshots? : false
Total countries to load 2
Total states to load 2
TypeError: Cannot read property 'length' of undefined
    at Load.run (/Users/bobby.white/projects/notmeta/src/commands/state_country/load.ts:125:74)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Load._run (/Users/bobby.white/projects/notmeta/node_modules/@salesforce/command/lib/sfdxCommand.js:91:40)
    at Config.runCommand (/Users/bobby.white/.local/share/sfdx/client/7.84.2-a2868a68d5/node_modules/@oclif/config/lib/config.js:173:24)
    at Main.run (/Users/bobby.white/.local/share/sfdx/client/7.84.2-a2868a68d5/node_modules/@oclif/command/lib/main.js:27:9)
    at Main._run (/Users/bobby.white/.local/share/sfdx/client/7.84.2-a2868a68d5/node_modules/@oclif/command/lib/command.js:43:20)
    at Object.run (/Users/bobby.white/.local/share/sfdx/client/7.84.2-a2868a68d5/dist/cli.js:32:20)
Country and State picklist load... ⣷ Country:S02[Iso Code:S02, IntVal:S02] successfully added !!!!
Country and State picklist load... ⣷ Country:S02[Iso Code:S02, IntVal:S02] successfully added !!!!
Country and State picklist load... done

**Expected Results:**   Command succeeds (or fails gracefully)
**Actual Results:**  Command fails with partial success.  The command appears to complete, but hangs.  I'm forced to kill the hanging command by Control-C from the terminal window.

Background:  I'm using the test CSV files that are part of this GitRepo.

**Comment by anandbn** [comment]
Fixed in https://github.com/anandbn/notmeta/commit/73ebda273a8954b5939d574a0295de829fbf5c9a
